### ISSUE TITLE
The function 'editMe' does not output the correct values

### ISSUE THREAD

**Issue by jhiester** [jhiester/pcgGit#1]

**Comment by davidl0673** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    hello
    <script>
        
        function editMe() {
    let x = 1;
    console.log(x);
    if (true) {
        let x = 2;
        console.log(x);
    }
}
        
editMe();   
        </script>
    
</body>
</html>`
